export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADJUST_ITEM_QTY: "ADDJUST_ITEM_QTY",
    LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
    TOGGLE_AMOUNT: "TOGGLE_AMOUNT",
    CLEAR_CARTS: "CLEAR_CARTS",
    TOTAL_MONEY: "TOTAL_MONEY",
    OPEN_SIDE_BAR: "OPEN_SIDE_BAR",
    CLOSE_SIDE_BAR: "CLOSE_SIDE_BAR",
    LOAD_PRODUCTS: "LOAD_PRODUCTS",
    SET_LISTVIEW: "SET_LISTVIEW",
    SET_GRIDVIEW: "SET_GRIDVIEW"
}